baseURL = "https://mitzu.io"
languageCode = "en-us"
title = "Mitzu"
theme = "kube"
description = "Your data. Your rules. Your friend, Mitzu. Mitzu is a library that let's you slice&dice and visualize your event data, while you remain in full control."
Paginate = 4
[Params]
  author = "" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"
  Tagline = "Your data. Your rules. Your friend, Mitzu."
  Description = "Mitzu is a library that let's you slice&dice and visualize your event data, while you remain in full control."
  Github = "https://github.com/mitzu-io/mitzu"

[[menu.main]]
    name = "Demo"
    weight = 10
    url = "/demo/"
[[menu.main]]
    name = "Quick start"
    weight = 0
    url = "/quick-start/"
[[menu.main]]
    name = "Docs"
    weight = 0
    url = "/docs/"
